### PR TITLE
Add entitlements support

### PR DESCRIPTION
**Pull request by cfergeau**
My project (https://github.com/crc-org/vfkit) needs entitlements to be able to use the virtualization framework.

This PR reworks special slot handling in the signing code and then adds entitlements support.

### CODE REVIEW

**Comment by dustin-decker** [comment]
Thanks for adding this, it's a timely addition for me! Looking forward to it in the next quill release.

**Comment by dustin-decker** [comment]
This worked perfectly for my needs! Thanks again, Christophe.

**Review by spiffcs — APPROVED** [review]

**Comment by spiffcs** [comment]
Thanks @cfergeau this also worked for me! We'll get this in and release Quill =)

**Comment by spiffcs** [comment]
I'm trying to replicate a failure I'm seeing locally in CI. Apologies, I want to isolate and figure out what's wrong before merging:

On my local when checking out this branch"
```
--- FAIL: TestSign (3.10s)
    --- FAIL: TestSign/sign_the_syft_binary_(with_a_password) (0.00s)
        sign_test.go:219:
            	Error Trace:	/Users/hal/GolandProjects/quill/quill/sign_test.go:219
            	Error:      	Received unexpected error:
            	            	unable to parse certificate 1 of 1: x509: certificate contains duplicate extensions
            	Test:       	TestSign/sign_the_syft_binary_(with_a_password)
```

**Comment by spiffcs** [comment]
👋 @cfergeau I tried to push to this branch to fix the Static Analysis error, but got an authentication problem against your branch.

Here is the diff, but you can also just run `make lint-fix`
```
diff --git a/quill/sign/entitlements.go b/quill/sign/entitlements.go
index 31e0a02..4eb8d57 100644
--- a/quill/sign/entitlements.go
+++ b/quill/sign/entitlements.go
@@ -4,8 +4,9 @@ import (
        "fmt"
        "hash"

-       "github.com/anchore/quill/quill/macho"
        "github.com/go-restruct/restruct"
+
+       "github.com/anchore/quill/quill/macho"
 )
```

**Comment by cfergeau** [comment]
> I'm trying to replicate a failure I'm seeing locally in CI. Apologies, I want to isolate and figure out what's wrong before merging:
> 
> On my local when checking out this branch"
> 
> ```
> --- FAIL: TestSign (3.10s)
>     --- FAIL: TestSign/sign_the_syft_binary_(with_a_password) (0.00s)
>         sign_test.go:219:
>             	Error Trace:	/Users/hal/GolandProjects/quill/quill/sign_test.go:219
>             	Error:      	Received unexpected error:
>             	            	unable to parse certificate 1 of 1: x509: certificate contains duplicate extensions
>             	Test:       	TestSign/sign_the_syft_binary_(with_a_password)
> ```

I'm seeing this issue with origin/master (+ https://github.com/anchore/quill/pull/314/commits/a7d454d10ebf221593f4d27e5bfc0a8fc769f38f ), this is not new in this PR.

**Comment by cfergeau** [comment]
> 👋 @cfergeau I tried to push to this branch to fix the Static Analysis error, but got an authentication problem against your branch.

"allow edit by maintainers" is checked in this PR, I don't know why you could not push.
I've fixed this now, though this comes with some additional lint changes as `make lint` was initially not working for me.

**Pull request merged**
